### ISSUE TITLE
Crash when opening menu "chatroom bookmark"

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#74]
2.1.2 F-Droid Xiaomi Android 10

```
11-14 08:52:06.194 21877 21877 D AndroidRuntime: Shutting down VM
11-14 08:52:06.194 21877 21877 E AndroidRuntime: FATAL EXCEPTION: main
11-14 08:52:06.194 21877 21877 E AndroidRuntime: Process: org.atalk.android, PID: 21877
11-14 08:52:06.194 21877 21877 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.ChatRoomBookmarksDialog.updateBookmarkFocus(ChatRoomBookmarksDialog.java:395)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.ChatRoomBookmarksDialog.initBookMarkForm(ChatRoomBookmarksDialog.java:377)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.ChatRoomBookmarksDialog.onItemSelected(ChatRoomBookmarksDialog.java:344)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.widget.AdapterView.fireOnSelected(Unknown Source:28)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.widget.AdapterView.dispatchOnItemSelected(Unknown Source:0)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.widget.AdapterView.access$300(Unknown Source:0)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.widget.AdapterView$SelectionNotifier.run(Unknown Source:48)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.os.Handler.handleCallback(Unknown Source:2)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:242)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:98)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
11-14 08:52:06.194 21877 21877 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275
```

**Comment by oroscobob** [comment]
2.1.2 F-Droid Resurrection Remix 5.8.5 Android 7.1.2 - Crash
2.1.2 F-Droid AOSP Android 7.1.1 - Crash

**Comment by cmeng-git** [comment]
> oroscobob
Please send the aTalk debug log. I need the debug log to understand the problem.

**Comment by cmeng-git** [comment]
Fix implemented in aTalk v2.1.3, please verify.

**Comment by oroscobob** [comment]
fdroid-debug - ok

**Comment by cmeng-git** [comment]
Thanks for your confirmation

**Comment by licaon-kter** [comment]
Still an issue in 2.1.3 F-Droid

```
12-04 08:36:58.493  2317  2317 D AndroidRuntime: Shutting down VM
12-04 08:36:58.493  2317  2317 E AndroidRuntime: FATAL EXCEPTION: main
12-04 08:36:58.493  2317  2317 E AndroidRuntime: Process: org.atalk.android, PID: 2317
12-04 08:36:58.493  2317  2317 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.ChatRoomBookmarksDialog.updateBookmarkFocus(ChatRoomBookmarksDialog.java:395)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.ChatRoomBookmarksDialog.initBookMarkForm(ChatRoomBookmarksDialog.java:377)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.ChatRoomBookmarksDialog.onItemSelected(ChatRoomBookmarksDialog.java:344)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.widget.AdapterView.fireOnSelected(Unknown Source:28)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.widget.AdapterView.dispatchOnItemSelected(Unknown Source:0)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.widget.AdapterView.access$300(Unknown Source:0)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.widget.AdapterView$SelectionNotifier.run(Unknown Source:48)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.os.Handler.handleCallback(Unknown Source:2)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:242)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:98)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
12-04 08:36:58.493  2317  2317 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
```

**Comment by cmeng-git** [comment]
Need to take a look again, look like the new implementation does not fixed the actual problem.

**Comment by cmeng-git** [comment]
aTalk v2.1.4 has been released with the fix. Please check and verify.

**Comment by licaon-kter** [comment]
Appears fixed. Thanks
