### ISSUE TITLE
Does not exit the "screen is blocked" mode.

### ISSUE THREAD

**Issue by oroscobob** [cmeng-git/atalk-android#79]
Does not exit the "screen is blocked" mode. (Samsung A50 to Samsung A50)
On other phones this does not happen.

```
2019-12-03 18:36:49.115 7378-7808/org.atalk.android W/g.atalk.androi: Long monitor contention with owner Smack DefaultReactor Thread #1 (7809) at void org.jivesoftware.smack.SmackReactor$Reactor.handleScheduledActionsOrPerformSelect()(SmackReactor.java:209) waiters=0 in void org.jivesoftware.smack.SmackReactor$Reactor.handleScheduledActionsOrPerformSelect() for 196.099s
---
2019-12-03 18:38:35.661 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 0
2019-12-03 18:38:35.784 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 1
2019-12-03 18:38:36.380 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 0
2019-12-03 18:38:36.438 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 1
2019-12-03 18:38:36.570 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 0
2019-12-03 18:38:36.632 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 1
2019-12-03 18:38:36.761 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 0
2019-12-03 18:38:36.846 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme pointer 1
2019-12-03 18:38:40.044 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme key 0
2019-12-03 18:38:40.089 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme key 1
2019-12-03 18:38:41.218 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme key 0
2019-12-03 18:38:41.312 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: ViewPostIme key 1
2019-12-03 18:38:42.244 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7e196af010 disconnect failed
2019-12-03 18:38:42.244 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7e065bf180, 0x7e196af000
2019-12-03 18:38:42.244 7378-7378/org.atalk.android D/ViewRootImpl@c93cf3d[VideoCallActivity]: dispatchDetachedFromWindow
2019-12-03 18:38:42.255 7378-7378/org.atalk.android D/InputTransport: Input channel destroyed: fd=160
2019-12-03 18:38:42.265 7378-7378/org.atalk.android D/SensorManager: unregisterListener ::   
2019-12-03 18:38:42.269 7378-7378/org.atalk.android E/ViewRootImpl: sendUserActionEvent() returned.
2019-12-03 18:38:42.269 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: stopped(true) old=false
2019-12-03 18:38:42.290 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7e064de010 disconnect failed
2019-12-03 18:38:42.290 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7ddfdf7980, 0x7e064de000
2019-12-03 18:38:42.300 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: Relayout returned: old=[0,0][1080,2214] new=[0,0][1080,2214] result=0x5 surface={false 0} changed=true
2019-12-03 18:38:42.305 7378-7378/org.atalk.android D/InputTransport: Input channel destroyed: fd=189
2019-12-03 18:38:42.402 7378-7378/org.atalk.android W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
2019-12-03 18:38:42.402 7378-7378/org.atalk.android W/System.err:     at android.view.ViewRootImpl.getHostVisibility(ViewRootImpl.java:1809)
2019-12-03 18:38:42.402 7378-7378/org.atalk.android W/System.err:     at android.view.ViewRootImpl.handleAppVisibility(ViewRootImpl.java:1445)
2019-12-03 18:38:42.403 7378-7378/org.atalk.android W/System.err:     at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4827)
2019-12-03 18:38:42.403 7378-7378/org.atalk.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-12-03 18:38:42.403 7378-7378/org.atalk.android W/System.err:     at android.os.Looper.loop(Looper.java:214)
2019-12-03 18:38:42.403 7378-7378/org.atalk.android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7076)
2019-12-03 18:38:42.403 7378-7378/org.atalk.android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-12-03 18:38:42.403 7378-7378/org.atalk.android W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-12-03 18:38:42.403 7378-7378/org.atalk.android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2019-12-03 18:38:42.453 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: Relayout returned: old=[0,0][1080,2214] new=[0,0][1080,2214] result=0x1 surface={false 0} changed=false
2019-12-03 18:38:46.937 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: Relayout returned: old=[0,0][1080,2214] new=[0,0][1080,2214] result=0x1 surface={false 0} changed=false
2019-12-03 18:38:46.937 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: stopped(false) old=true
2019-12-03 18:38:46.941 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: stopped(false) old=false
2019-12-03 18:38:46.949 7378-7378/org.atalk.android D/SensorManager: registerListener :: 1600479602, Ear Hover Proximity Sensor, 200000, 0,  
2019-12-03 18:38:46.951 7378-7378/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-03 18:38:46.963 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: Relayout returned: old=[0,0][1080,2214] new=[0,0][1080,2214] result=0x7 surface={true 541271646208} changed=true
2019-12-03 18:38:46.964 7378-7438/org.atalk.android D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2019-12-03 18:38:46.964 7378-7438/org.atalk.android D/OpenGLRenderer: eglCreateWindowSurface = 0x7ddfdf7980, 0x7e064de010
2019-12-03 18:38:46.966 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2019-12-03 18:38:46.968 7378-7378/org.atalk.android D/InputMethodManager: prepareNavigationBarInfo() DecorView@7e7656[VideoCallActivity]
2019-12-03 18:38:46.968 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:38:46.969 7378-7378/org.atalk.android D/InputMethodManager: prepareNavigationBarInfo() DecorView@7e7656[VideoCallActivity]
2019-12-03 18:38:46.969 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:38:46.969 7378-7378/org.atalk.android V/InputMethodManager: Starting input: tba=org.atalk.android ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2019-12-03 18:38:46.969 7378-7378/org.atalk.android D/InputMethodManager: startInputInner - Id : 0
2019-12-03 18:38:46.969 7378-7378/org.atalk.android I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-12-03 18:38:46.970 7378-7378/org.atalk.android D/InputTransport: Input channel constructed: fd=92
2019-12-03 18:38:47.011 7378-7378/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-03 18:38:49.765 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: ViewPostIme pointer 0
2019-12-03 18:38:49.823 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: ViewPostIme pointer 1
2019-12-03 18:38:49.845 7378-7378/org.atalk.android D/SensorManager: unregisterListener ::   
2019-12-03 18:38:49.854 7378-7378/org.atalk.android D/ViewRootImpl@63ef6f2[VideoCallActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2019-12-03 18:38:49.854 7378-7378/org.atalk.android D/InputMethodManager: prepareNavigationBarInfo() DecorView@7e7656[VideoCallActivity]
2019-12-03 18:38:49.855 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:38:49.856 7378-7378/org.atalk.android D/ViewRootImpl@12f43ab[aTalk]: stopped(false) old=true
2019-12-03 18:38:49.859 7378-7378/org.atalk.android D/ViewRootImpl@12f43ab[aTalk]: stopped(false) old=false
```
--------------------------------------------------------

Switching to the phone’s home screen doesn’t change anything.

I sent a message to the blocked phone, I switched to the message from the phone notification menu. Atalk unlocked. Below is the log of this action.

-------------------------------------------------------
019-12-03 18:47:52.329 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:47:52.330 7378-7378/org.atalk.android D/InputMethodManager: prepareNavigationBarInfo() DecorView@f455404[VideoCallActivity]
2019-12-03 18:47:52.330 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:47:52.330 7378-7378/org.atalk.android V/InputMethodManager: Starting input: tba=org.atalk.android ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2019-12-03 18:47:52.330 7378-7378/org.atalk.android D/InputMethodManager: startInputInner - Id : 0
2019-12-03 18:47:52.330 7378-7378/org.atalk.android I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-12-03 18:47:52.333 7378-7378/org.atalk.android D/InputTransport: Input channel constructed: fd=152
2019-12-03 18:47:53.157 7378-7378/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-03 18:47:54.311 7378-7378/org.atalk.android D/ViewRootImpl@2af7eb3[VideoCallActivity]: ViewPostIme pointer 0
2019-12-03 18:47:54.506 7378-7378/org.atalk.android D/ViewRootImpl@2af7eb3[VideoCallActivity]: ViewPostIme pointer 1
2019-12-03 18:47:55.032 7378-7378/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-03 18:47:55.442 7378-7378/org.atalk.android D/ViewRootImpl@2af7eb3[VideoCallActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2019-12-03 18:47:55.442 7378-7378/org.atalk.android D/InputMethodManager: prepareNavigationBarInfo() DecorView@f455404[VideoCallActivity]
2019-12-03 18:47:55.442 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:47:55.897 7378-7378/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-03 18:47:57.528 7378-7378/org.atalk.android D/SensorManager: unregisterListener ::   
2019-12-03 18:47:57.540 7378-7378/org.atalk.android W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@4ca8ce
2019-12-03 18:47:57.548 7378-7378/org.atalk.android I/DecorView: createDecorCaptionView >> DecorView@5154ee8[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
2019-12-03 18:47:57.581 7378-7378/org.atalk.android D/(NotificationPopupHandler.java:136)#removeNotification: Removing notification: 1282549867
2019-12-03 18:47:57.597 7378-7378/org.atalk.android D/InputTransport: Input channel constructed: fd=131
2019-12-03 18:47:57.597 7378-7378/org.atalk.android D/ViewRootImpl@576e38c[ChatActivity]: setView = DecorView@5154ee8[ChatActivity] TM=true MM=false
2019-12-03 18:47:57.613 7378-7378/org.atalk.android D/(ChatFragment.java:480)#initChatController: Skipping null controller init...
2019-12-03 18:47:57.628 7378-7378/org.atalk.android D/(ChatFragment.java:464)#initChatController: Init controller: 177056305
2019-12-03 18:47:57.628 7378-7378/org.atalk.android D/(ChatController.java:159)#onShow: ChatController attached to 177056305
2019-12-03 18:47:57.653 7378-7378/org.atalk.android D/ViewRootImpl@576e38c[ChatActivity]: Relayout returned: old=[0,0][1080,2214] new=[0,0][1080,2214] result=0x7 surface={true 540784033792} changed=true
2019-12-03 18:47:57.659 7378-7438/org.atalk.android D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2019-12-03 18:47:57.659 7378-7438/org.atalk.android D/OpenGLRenderer: eglCreateWindowSurface = 0x7e01bb9200, 0x7de93d8010
2019-12-03 18:47:57.661 7378-7378/org.atalk.android D/AbsListView:  in onLayout changed 
2019-12-03 18:47:57.661 7378-7378/org.atalk.android D/AbsListView:  in onLayout changed 
2019-12-03 18:47:57.669 7378-7819/org.atalk.android D/SMACK: SENT (0): 
    <iq to='user2@xxxxxxxxxx.com' id='X5GTV-408' type='get'>
      <query xmlns='http://jabber.org/protocol/disco#info' node='eu.siacs.conversations.axolotl.devicelist'>
      </query>
    </iq>
2019-12-03 18:47:57.708 7378-7378/org.atalk.android D/ViewRootImpl@576e38c[ChatActivity]: MSG_RESIZED: frame=[0,0][1080,2214] ci=[0,83][0,0] vi=[0,83][0,0] or=1
2019-12-03 18:47:57.724 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7e06366010 disconnect failed
2019-12-03 18:47:57.724 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7e19708f80, 0x7e06366000
2019-12-03 18:47:57.731 7378-7378/org.atalk.android D/ViewRootImpl@2af7eb3[VideoCallActivity]: Relayout returned: old=[0,83][1080,2214] new=[0,83][1080,2214] result=0x5 surface={false 0} changed=true
2019-12-03 18:47:57.732 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7de27a6010 disconnect failed
2019-12-03 18:47:57.732 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7e1970ce80, 0x7de27a6000
2019-12-03 18:47:57.739 7378-7378/org.atalk.android D/ViewRootImpl@8f0036c[VideoCallActivity]: Relayout returned: old=[0,83][1080,2214] new=[0,83][1080,2214] result=0x5 surface={false 0} changed=true
2019-12-03 18:47:57.741 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7de2796010 disconnect failed
2019-12-03 18:47:57.741 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7e01568600, 0x7de2796000
2019-12-03 18:47:57.749 7378-7378/org.atalk.android D/ViewRootImpl@3ea4c41[VideoCallActivity]: Relayout returned: old=[0,83][1080,2214] new=[0,83][1080,2214] result=0x5 surface={false 0} changed=true
2019-12-03 18:47:57.750 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7de9352010 disconnect failed
2019-12-03 18:47:57.750 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7e01bb9380, 0x7de9352000
2019-12-03 18:47:57.757 7378-7378/org.atalk.android D/ViewRootImpl@660ecc2[VideoCallActivity]: Relayout returned: old=[0,83][1080,2214] new=[0,83][1080,2214] result=0x5 surface={false 0} changed=true
2019-12-03 18:47:57.759 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7e05be8010 disconnect failed
2019-12-03 18:47:57.759 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7ddfbfd680, 0x7e05be8000
2019-12-03 18:47:57.767 7378-7378/org.atalk.android D/ViewRootImpl@6019a3f[VideoCallActivity]: Relayout returned: old=[0,83][1080,2214] new=[0,83][1080,2214] result=0x5 surface={false 0} changed=true
2019-12-03 18:47:57.770 7378-7438/org.atalk.android W/libEGL: EGLNativeWindowType 0x7de93cc010 disconnect failed
2019-12-03 18:47:57.770 7378-7438/org.atalk.android D/OpenGLRenderer: eglDestroySurface = 0x7dfed4ff00, 0x7de93cc000
2019-12-03 18:47:57.778 7378-7378/org.atalk.android D/ViewRootImpl@f099c9f[VideoCallActivity]: Relayout returned: old=[0,0][1080,2214] new=[0,0][1080,2214] result=0x5 surface={false 0} changed=true
2019-12-03 18:47:57.784 7378-7378/org.atalk.android D/ViewRootImpl@2af7eb3[VideoCallActivity]: stopped(true) old=false
2019-12-03 18:47:57.784 7378-7378/org.atalk.android D/ViewRootImpl@8f0036c[VideoCallActivity]: stopped(true) old=false
2019-12-03 18:47:57.784 7378-7378/org.atalk.android D/ViewRootImpl@3ea4c41[VideoCallActivity]: stopped(true) old=false
2019-12-03 18:47:57.784 7378-7378/org.atalk.android D/ViewRootImpl@660ecc2[VideoCallActivity]: stopped(true) old=false
2019-12-03 18:47:57.784 7378-7378/org.atalk.android D/ViewRootImpl@6019a3f[VideoCallActivity]: stopped(true) old=false
2019-12-03 18:47:57.784 7378-7378/org.atalk.android D/ViewRootImpl@f099c9f[VideoCallActivity]: stopped(true) old=false
2019-12-03 18:47:57.802 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <iq xml:lang='ru-RU' to='a50@xxxxxxxxxx.com/atalk' from='user2@xxxxxxxxxx.com' type='result' id='X5GTV-408'>
      <query node='eu.siacs.conversations.axolotl.devicelist' xmlns='http://jabber.org/protocol/disco#info'>
        <identity type='pep' category='pubsub'/>
        <identity type='leaf' category='pubsub'/>
        <identity type='registered' category='account'/>
        <feature var='http://jabber.org/protocol/pubsub'/>
        <feature var='http://jabber.org/protocol/pubsub#create-nodes'/>
        <feature var='http://jabber.org/protocol/pubsub#auto-create'/>
        <feature var='http://jabber.org/protocol/pubsub#auto-subscribe'/>
        <feature var='http://jabber.org/protocol/pubsub#delete-nodes'/>
        <feature var='http://jabber.org/protocol/pubsub#delete-items'/>
        <feature var='http://jabber.org/protocol/pubsub#filtered-notifications'/>
        <feature var='http://jabber.org/protocol/pubsub#modify-affiliations'/>
        <feature var='http://jabber.org/protocol/pubsub#outcast-affiliation'/>
        <feature var='http://jabber.org/protocol/pubsub#persistent-items'/>
        <feature var='http://jabber.org/protocol/pubsub#publish'/>
        <feature var='http://jabber.org/protocol/pubsub#publish-options'/>
        <feature var='http://jabber.org/protocol/pubsub#purge-nodes'/>
        <feature var='http://jabber.org/protocol/pubsub#retract-items'/>
        <feature var='http://jabber.org/protocol/pubsub#retrieve-affiliations'/>
        <feature var='http://jabber.org/protocol/pubsub#retrieve-items'/>
        <feature var='http://jabber.org/protocol/pubsub#retrieve-subscriptions'/>
        <feature var='http://jabber.org/protocol/pubsub#subscribe'/>
      </query>
    </iq>
2019-12-03 18:47:57.804 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <r xmlns='urn:xmpp:sm:3'/>
2019-12-03 18:47:57.805 7378-7819/org.atalk.android D/SMACK: SENT (0): 
    <iq to='user2@xxxxxxxxxx.com' id='X5GTV-410' type='get'>
      <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <items node='eu.siacs.conversations.axolotl.devicelist'/>
      </pubsub>
    </iq>
    <a xmlns='urn:xmpp:sm:3' h='182'/>
2019-12-03 18:47:57.920 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <iq xml:lang='ru-RU' to='a50@xxxxxxxxxx.com/atalk' from='user2@xxxxxxxxxx.com' type='result' id='X5GTV-410'>
      <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <items node='eu.siacs.conversations.axolotl.devicelist'>
          <item id='625A4F92A2FA6'>
            <list xmlns='eu.siacs.conversations.axolotl'>
              <device id='1395984225'/>
              <device id='795999510'/>
            </list>
          </item>
        </items>
      </pubsub>
    </iq>
2019-12-03 18:47:57.922 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <r xmlns='urn:xmpp:sm:3'/>
2019-12-03 18:47:57.922 7378-7819/org.atalk.android D/SMACK: SENT (0): 
    <a xmlns='urn:xmpp:sm:3' h='183'/>
2019-12-03 18:47:57.924 7378-17659/org.atalk.android D/(DatabaseBackend.java:1011)#storeCachedDeviceList: Identities table - updating for activeDevice: user2@xxxxxxxxxx.com:[1395984225, 795999510]
2019-12-03 18:47:57.925 7378-17659/org.atalk.android D/(DatabaseBackend.java:1024)#storeCachedDeviceList: Identities table - create new activeDevice: user2@xxxxxxxxxx.com:1395984225 
2019-12-03 18:47:57.937 7378-17659/org.atalk.android I/(DatabaseBackend.java:1040)#storeCachedDeviceList: Identities table updated for inactiveDevice: user2@xxxxxxxxxx.com:[]
2019-12-03 18:47:58.036 7378-7378/org.atalk.android D/ViewRootImpl@576e38c[ChatActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2019-12-03 18:47:58.036 7378-7378/org.atalk.android D/InputMethodManager: prepareNavigationBarInfo() DecorView@5154ee8[ChatActivity]
2019-12-03 18:47:58.036 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:47:58.041 7378-7378/org.atalk.android D/InputMethodManager: prepareNavigationBarInfo() DecorView@5154ee8[ChatActivity]
2019-12-03 18:47:58.041 7378-7378/org.atalk.android D/InputMethodManager: getNavigationBarColor() -855310
2019-12-03 18:47:58.041 7378-7378/org.atalk.android V/InputMethodManager: Starting input: tba=org.atalk.android ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2019-12-03 18:47:58.041 7378-7378/org.atalk.android D/InputMethodManager: startInputInner - Id : 0
2019-12-03 18:47:58.041 7378-7378/org.atalk.android I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-12-03 18:47:58.047 7378-7378/org.atalk.android D/InputTransport: Input channel constructed: fd=89
2019-12-03 18:47:58.047 7378-7378/org.atalk.android D/InputTransport: Input channel destroyed: fd=152
2019-12-03 18:47:58.142 7378-7819/org.atalk.android D/SMACK: SENT (0): 
    <message to='user2@xxxxxxxxxx.com/atalk' id='X5GTV-412'>
      <active xmlns='http://jabber.org/protocol/chatstates'/>
      <origin-id xmlns='urn:xmpp:sid:0' id='ITEA-J2J5-B41U-T'/>
    </message>
    <r xmlns='urn:xmpp:sm:3'/>
2019-12-03 18:47:58.251 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <a h='168' xmlns='urn:xmpp:sm:3'/>
2019-12-03 18:48:12.928 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <message xml:lang='ru-RU' to='a50@xxxxxxxxxx.com/atalk' from='user2@xxxxxxxxxx.com/atalk' type='chat' id='B248I-266'>
      <inactive xmlns='http://jabber.org/protocol/chatstates'/>
      <origin-id xmlns='urn:xmpp:sid:0' id='3RZ1-SGUK-RLXP-R'/>
    </message>
2019-12-03 18:48:12.936 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <r xmlns='urn:xmpp:sm:3'/>
2019-12-03 18:48:12.937 7378-17457/org.atalk.android D/(OperationSetChatStateNotificationsJabberImpl.java:418)#stateChanged: ChatState Event: user2@xxxxxxxxxx.com/atalk is in 'inactive'
2019-12-03 18:48:12.938 7378-7819/org.atalk.android D/SMACK: SENT (0): 
    <a xmlns='urn:xmpp:sm:3' h='184'/>
2019-12-03 18:48:28.165 7378-7819/org.atalk.android D/SMACK: SENT (0): 
    <message to='user2@xxxxxxxxxx.com/atalk' id='X5GTV-414'>
      <inactive xmlns='http://jabber.org/protocol/chatstates'/>
      <origin-id xmlns='urn:xmpp:sid:0' id='EDGP-TQSU-E9LC-7'/>
    </message>
    <r xmlns='urn:xmpp:sm:3'/>
2019-12-03 18:48:28.286 7378-7820/org.atalk.android D/SMACK: RECV (0): 
    <a h='169' xmlns='urn:xmpp:sm:3'/>

**Comment by cmeng-git** [comment]
aTalk "SCREEN IS BLOCKED" or turn off during call depends on the proper operation of the proximity sensor.

Please install "Sensors Test" from EXA Tools to verify that the proximity sensor does work in your phone without any special handling from app.

Also please note:
Caution Cases, covers and improperly installed screen protectors may interfere with proximity sensor function.
The above case did happened on one of the aTalk user device.

I found that aTalk running on Note-10 is also having this problem, due to the reason below:
[PSA: Your Galaxy Note 10 Doesn’t Have a Dead Pixel, That’s the Proximity Sensor](https://www.droid-life.com/2019/08/26/psa-galaxy-note-10-proximity-sensor-not-dead-pixel/)

If the correct operation of proximity sensor on an android device requires specific handling for that device e.g. Note-10, then aTalk "SCREEN IS BLOCKED" feature will not work properly on such device.

**Comment by oroscobob** [comment]
With the proximity sensor, everything is fine. It works in other applications.

This problem happens on two A50 phones.

When the screen is locked, you can go to the incoming message from the notification menu. But when you press the back button in the activity message, you return to the locked screen.

The solution to this problem is to stop the application in the phone settings.

**Comment by cmeng-git** [comment]
I still would like you to verify your device proximity with the sensor tester. A constant black screen means the proximity is blocked by some object.

**Comment by oroscobob** [comment]
The first Samsung А50 has a protector film. Another Samsung A50 is new. On both Samsungs there is a signal. The signal works with a proximity sensor. WhatsApp also works on both Samsung A50s.

**Comment by cmeng-git** [comment]
I still need you to tell me the result from the sensor tester.

**Comment by oroscobob** [comment]
I checked with a few applications the results of the sensors on both Samsung A50 phones. Distance is 5 cm. Both sensors work.

Do you need any specific results?

**Comment by cmeng-git** [comment]
Please send me a screen snapshot of the "sensor tester" running showing the proximity test result.
aTalk will turn off/on screen according to the "sensor tester" result output.

I found that aTalk running on my Note-10 is also having this problem, due to the reason below:
[PSA: Your Galaxy Note 10 Doesn’t Have a Dead Pixel, That’s the Proximity Sensor](https://www.droid-life.com/2019/08/26/psa-galaxy-note-10-proximity-sensor-not-dead-pixel/)

I need to know if the A50 behaves like Note-10 where only Samsung app knows how to control and activate the proximity sensor during call. OR the activation of the proximity sensor is a standard function call documented in android libraries, allowing third party app to use the proximity sensor.

Below are some of the information online:
https://r2.community.samsung.com/t5/Galaxy-A/Galaxy-A50-proximity-sensor-bug-during-call/td-p/2211036

https://forum.xda-developers.com/galaxy-note-10+/help/proximity-sensor-t3960197

> The proximity sensor is indeed under the screen and a pixel has to be turned off for it to work properly. This means proximity apps will not work properly any more unless Samsung writes them.
> 
> So Samsung turns off a pixel so that the Proximity Sensor can see/work (like during a call) - and that means my Tasker screen off will not work. Wonder if there is a Tasker "if front camera covered".. gonna go look that up now.

**Comment by oroscobob** [comment]
Today, the sensor works on both phones. Unusual problem.

2019-12-05 15:18:52.338 6971-6971/org.atalk.android I/(ProximitySensorFragment.java:78)#onResume: Using proximity sensor: Ear Hover Proximity Sensor
2019-12-05 15:18:52.348 6971-6971/org.atalk.android D/SensorManager: registerListener :: 1600479602, Ear Hover Proximity Sensor, 66667, 0,  
2019-12-05 15:18:52.360 6971-6971/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-05 15:18:53.247 6971-6971/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-05 15:18:56.595 6971-6971/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-05 15:18:58.729 6971-6971/org.atalk.android D/SensorManager: Proximity, val = 0.0  [close]
2019-12-05 15:18:59.807 6971-6971/org.atalk.android D/SensorManager: Proximity, val = 5.0  [far]
2019-12-05 15:19:02.644 6971-6971/org.atalk.android D/SensorManager: Proximity, val = 0.0  [close]

**Comment by cmeng-git** [comment]
Look like you have resolved the problem. Will close the issue.
